version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    # environment:

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:99:fd:b0:f7:5d:47:bb:da:01:b6:6c:98:f1:6c:d6"
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Build
          command: |
            rustc --version --verbose
            cargo --version
            cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Check formatting
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
