"""Calculate XYZ↔sRGB conversion matrices.

See http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_Lab.html for description
of the calculation.  Code uses rational numbers throughout the calculation to
avoid rounding errors creeping in.  Coefficients are converted to floating point
only at the end for printing.
"""

__author__ = 'Michal Nazarewicz <mina86@mina86.com>'

import collections
import fractions


def inverse(m):
    def signed_minor_det(row, col):
        a, b, c, d = [m[r][c]
                      for r in (0, 1, 2) if r != row
                      for c in (0, 1, 2) if c != col]
        res = a * d - b * c
        return res if (row ^ col) & 1 == 0 else -res

    signed_minors = [
        [signed_minor_det(row, col) for col in (0, 1, 2)] for row in (0, 1, 2)
    ]
    det = sum(m[0][col] * signed_minors[0][col] for col in (0, 1, 2))
    return [[signed_minors[col][row] / det for col in (0, 1, 2)]
            for row in (0, 1, 2)]


def print_let(m, out_names, in_names):
    print('    // Generated by srgb-matrices.py')
    for var, row in zip(out_names, m):
        print('    let {} = mul3({}, {});'.format(
            var, ', '.join(in_names), ', '.join(str(float(v)) for v in row)))


def main():
    xy = collections.namedtuple('xy', 'x y')

    # https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.709-6-201506-I!!PDF-E.pdf
    r = xy(fractions.Fraction(64, 100), fractions.Fraction(33, 100))
    g = xy(fractions.Fraction(30, 100), fractions.Fraction(60, 100))
    b = xy(fractions.Fraction(15, 100), fractions.Fraction(6, 100))

    w = xy(fractions.Fraction(312713, 1000000),
           fractions.Fraction(329016, 1000000))

    w = (w.x / w.y, 1, (1 - w.x - w.y) / w.y)

    # http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html
    matrix = [[c.x / c.y for c in (r, g, b)],
              [1, 1, 1],
              [(1 - c.x - c.y) / c.y for c in (r, g, b)]]
    inv = inverse(matrix)
    s = tuple(sum(w[c] * inv[r][c] for c in (0, 1, 2)) for r in (0, 1, 2))
    m = [[matrix[r][c] * s[c] for c in (0, 1, 2)] for r in (0, 1, 2)]

    print('// Generated by srgb-matrices.py\n'
          'const WHITE_X: f32 = {};\n'
          'const WHITE_Z: f32 = {};\n'.format(float(w[0]), float(w[2])))

    print_let(m, 'xyz', 'rgb')
    print()

    print_let(inverse(m), 'rgb', 'xyz')


if __name__ == '__main__':
    main()
